/**
 * main.js
 *
 */

document.addEventListener('DOMContentLoaded', function(eve) {
  var main = document.querySelector('main');
  main.insertAdjacentHTML('afterbegin', '<p>This page is generated by EJS.</p>');
}, false);
